@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Mar 23 19:25:47 -0700 2021
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 61204bc8b9294ab3a85cecbc1f5b018b --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot textio_tb_behav xil_defaultlib.textio_tb -log elaborate.log"
call xelab  -wto 61204bc8b9294ab3a85cecbc1f5b018b --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot textio_tb_behav xil_defaultlib.textio_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
